# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 167e830a92e29c0bafeed177552d0f4adbd54011e4c2c4d3eb00d9b5fdb601e64e42108e565dc723b8662f84f6ffdf66a77c7790ac71f064b49905a2df01765e

test:
  secret_key_base: 53418f38cceeafa7c230e6da475ccf8a3819f4f16766ef2e0cdc7dc3b7d325fb55111759fd9e1fbc88061d2a5e60ebe997ea66525bdc4aeaf4cc7fc5a8b76844

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
